### ISSUE TITLE
Question about the implementation details

### ISSUE THREAD

**Issue by speedcell4** [wenyudu/SDLM#1]
Hi, thanks for the "coming soon" source code.

I have not figured out what are the "non-leaf nodes" in Figure 2, does that mean you truly add a special token, say "\<sep>", between words? Thus your actual input sentence looks like "I \<sep> ate \<sep> an \<sep> apple"?

**Comment by wenyudu** [comment]
Hi, thanks for your interest and patience. 

We are working on followup work and the source code will be released together afterward. In terms of your question regarding figure2, we didn't add tokens. Instead, we simply feed raw sentences as inputs and calculate one scalar distance for each pair of adjacent words. We just follow what previous literature [1] did.

[1] Yikang Shen, Shawn Tan, Alessandro Sordoni, and Aaron Courville. 2018. Ordered neurons: Integrating tree structures into recurrent neural networks.
